kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-gitlab
  namespace: public-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
