kind: Service
apiVersion: v1
metadata:
  labels:
    name: gitlab
    type: LoadBalancer
  name: gitlab-balancer
  namespace: public-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32545
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: 22
#    nodePort: 32022
  selector:
    name: gitlab
  type: NodePort
